In [1]:
import numpy as np 
import pandas as pd 
from mlxtend.frequent_patterns import apriori, association_rules

In [ ]:
poi_data = pd.read_csv('../Datasets/POIdata_cityB.csv')
categories = pd.read_csv('../Datasets/POI_datacategories.csv', header=None)

In [3]:
poi_data['grid_id'] = poi_data['x'].astype(str) + "_" + poi_data['y'].astype(str)
grid_baskets = poi_data.groupby('grid_id')['category'].apply(list)

for basket in grid_baskets:
    basket = list(set(basket))

grid_baskets

grid_id
100_102                     [83, 48, 38, 34, 63, 76, 62, 74]
100_103    [59, 63, 48, 35, 60, 79, 55, 41, 47, 67, 52, 8...
100_104    [59, 48, 54, 76, 79, 74, 37, 60, 65, 58, 55, 6...
100_117                                             [79, 81]
100_118    [62, 35, 74, 66, 36, 52, 55, 4, 51, 79, 54, 48...
                                 ...
9_40                                            [54, 74, 73]
9_41                                            [69, 60, 73]
9_42                 [59, 74, 51, 73, 57, 41, 4, 63, 56, 58]
9_43       [69, 41, 48, 82, 74, 18, 66, 34, 53, 40, 54, 7...
9_44             [54, 48, 60, 74, 58, 9, 79, 41, 82, 59, 69]
Name: category, Length: 9124, dtype: object

In [4]:
one_hot_list = []

for i in range(len(grid_baskets)):
    row = []
    for j in range(len(categories)):
        row.append(0)
    one_hot_list.append(row)


for basket_index in range(len(grid_baskets)):
    for category_index in grid_baskets[basket_index]:
        one_hot_list[basket_index][category_index-1] = 1

one_hot_df = pd.DataFrame(one_hot_list, columns=categories[0])
one_hot_df

,Food,Shopping,Entertainment,Japanese restaurant,Western restaurant,Eat all you can restaurant,Chinese restaurant,Indian restaurant,Ramen restaurant,Curry restaurant,...,Accountant Office,IT Office,Publisher Office,Building Material,Gardening,Heavy Industry,NPO,Utility Copany,Port,Research Facility
0,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
2,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,1,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
4,0,0,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9119,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9120,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9121,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9122,0,0,0,1,0,0,1,0,0,0,...,1,0,1,1,0,1,1,0,0,0
9123,0,0,0,0,0,0,0,0,1,0,...,0,0,0,1,0,0,1,0,0,0

In [5]:
grid_baskets_df = grid_baskets.reset_index()
grid_baskets_df.columns = ['grid_id', 'categories']
print(grid_baskets_df)

      grid_id                                         categories
0     100_102                   [83, 48, 38, 34, 63, 76, 62, 74]
1     100_103  [59, 63, 48, 35, 60, 79, 55, 41, 47, 67, 52, 8...
2     100_104  [59, 48, 54, 76, 79, 74, 37, 60, 65, 58, 55, 6...
3     100_117                                           [79, 81]
4     100_118  [62, 35, 74, 66, 36, 52, 55, 4, 51, 79, 54, 48...
...       ...                                                ...
9119     9_40                                       [54, 74, 73]
9120     9_41                                       [69, 60, 73]
9121     9_42            [59, 74, 51, 73, 57, 41, 4, 63, 56, 58]
9122     9_43  [69, 41, 48, 82, 74, 18, 66, 34, 53, 40, 54, 7...
9123     9_44        [54, 48, 60, 74, 58, 9, 79, 41, 82, 59, 69]

[9124 rows x 2 columns]

In [6]:
grid_baskets_df = grid_baskets_df.join(one_hot_df)
grid_baskets_df.drop(['categories'], axis='columns', inplace=True)
grid_baskets_df.set_index('grid_id', inplace=True)
grid_baskets_df

,Food,Shopping,Entertainment,Japanese restaurant,Western restaurant,Eat all you can restaurant,Chinese restaurant,Indian restaurant,Ramen restaurant,Curry restaurant,...,Accountant Office,IT Office,Publisher Office,Building Material,Gardening,Heavy Industry,NPO,Utility Copany,Port,Research Facility
grid_id,,,,,,,,,,,,,,,,,,,,,
100_102,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
100_103,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
100_104,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,1,0,0,0,0
100_117,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
100_118,0,0,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9_40,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9_41,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9_42,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9_43,0,0,0,1,0,0,1,0,0,0,...,1,0,1,1,0,1,1,0,0,0
9_44,0,0,0,0,0,0,0,0,1,0,...,0,0,0,1,0,0,1,0,0,0

In [8]:
freq_items = apriori(grid_baskets_df, min_support=0.1, use_colnames=True)

rules = association_rules(freq_items, metric ="lift", min_threshold = 1) 
rules = rules.sort_values(['confidence', 'lift'], ascending =[False, False]) 
print(rules.head())

                           antecedents          consequents  \
101    (Hair Salon, Building Material)    (Transit Station)
16                              (Bank)    (Transit Station)
12                          (Laundry )    (Transit Station)
36                       (Real Estate)  (Building Material)
112  (Home Appliances, Heavy Industry)  (Building Material)

     antecedent support  consequent support   support  confidence      lift  \
101            0.123520            0.359711  0.100395    0.812777  2.259531
16             0.133056            0.359711  0.105984    0.796540  2.214392
12             0.162210            0.359711  0.121219    0.747297  2.077496
36             0.163744            0.270934  0.121328    0.740964  2.734852
112            0.145989            0.270934  0.107628    0.737237  2.721097

     leverage  conviction  zhangs_metric
101  0.055963    3.419934       0.635988
16   0.058123    3.147009       0.632577
12   0.062870    2.533765       0.619070
36   0.076965    2.814535       0.758559
112  0.068075    2.774618       0.740624

c:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:109: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(