In [1]:
import numpy as np 
import pandas as pd 
from mlxtend.frequent_patterns import apriori, association_rules

In [2]:
poi_data = pd.read_csv('../Datasets/POIdata_cityC.csv')
categories = pd.read_csv('../Datasets/POI_datacategories.csv', header=None)

In [3]:
poi_data['grid_id'] = poi_data['x'].astype(str) + "_" + poi_data['y'].astype(str)
grid_baskets = poi_data.groupby('grid_id')['category'].apply(list)

for basket in grid_baskets:
    basket = list(set(basket))

grid_baskets

grid_id
101_200                                        [74]
102_188                                        [18]
108_161                                    [80, 81]
109_162                                        [48]
10_105                                     [80, 76]
                             ...
9_197      [48, 76, 47, 59, 53, 69, 79, 58, 54, 63]
9_4                                            [73]
9_5                    [61, 82, 66, 41, 73, 69, 72]
9_6                                            [62]
9_90                                           [74]
Name: category, Length: 3251, dtype: object

In [4]:
one_hot_list = []

for i in range(len(grid_baskets)):
    row = []
    for j in range(len(categories)):
        row.append(0)
    one_hot_list.append(row)


for basket_index in range(len(grid_baskets)):
    for category_index in grid_baskets[basket_index]:
        one_hot_list[basket_index][category_index-1] = 1

one_hot_df = pd.DataFrame(one_hot_list, columns=categories[0])
one_hot_df

,Food,Shopping,Entertainment,Japanese restaurant,Western restaurant,Eat all you can restaurant,Chinese restaurant,Indian restaurant,Ramen restaurant,Curry restaurant,...,Accountant Office,IT Office,Publisher Office,Building Material,Gardening,Heavy Industry,NPO,Utility Copany,Port,Research Facility
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3246,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
3247,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3248,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3249,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3250,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
grid_baskets_df = grid_baskets.reset_index()
grid_baskets_df.columns = ['grid_id', 'categories']
print(grid_baskets_df)

      grid_id                                categories
0     101_200                                      [74]
1     102_188                                      [18]
2     108_161                                  [80, 81]
3     109_162                                      [48]
4      10_105                                  [80, 76]
...       ...                                       ...
3246    9_197  [48, 76, 47, 59, 53, 69, 79, 58, 54, 63]
3247      9_4                                      [73]
3248      9_5              [61, 82, 66, 41, 73, 69, 72]
3249      9_6                                      [62]
3250     9_90                                      [74]

[3251 rows x 2 columns]

In [6]:
grid_baskets_df = grid_baskets_df.join(one_hot_df)
grid_baskets_df.drop(['categories'], axis='columns', inplace=True)
grid_baskets_df.set_index('grid_id', inplace=True)
grid_baskets_df

,Food,Shopping,Entertainment,Japanese restaurant,Western restaurant,Eat all you can restaurant,Chinese restaurant,Indian restaurant,Ramen restaurant,Curry restaurant,...,Accountant Office,IT Office,Publisher Office,Building Material,Gardening,Heavy Industry,NPO,Utility Copany,Port,Research Facility
grid_id,,,,,,,,,,,,,,,,,,,,,
101_200,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
102_188,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108_161,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,0,0,0,0
109_162,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10_105,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9_197,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
9_4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9_5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
9_6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9_90,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
freq_items = apriori(grid_baskets_df, min_support=0.25, use_colnames=True)

rules = association_rules(freq_items, metric ="lift", min_threshold = 1) 
rules = rules.sort_values(['confidence', 'lift'], ascending =[False, False]) 
print(rules.head())

                          antecedents        consequents  antecedent support  \
184   (Hair Salon, Building Material)  (Transit Station)            0.271301
160         (Real Estate, Hair Salon)  (Transit Station)            0.285451
165  (Accountant Office, Real Estate)  (Transit Station)            0.278376
147  (Elderly Care Home, Real Estate)  (Transit Station)            0.272224
21                         (Hospital)  (Transit Station)            0.301446

     consequent support   support  confidence      lift  leverage  conviction  \
184            0.571516  0.255306    0.941043  1.646572  0.100253    7.267740
160            0.571516  0.267302    0.936422  1.638487  0.104163    6.739538
165            0.571516  0.258382    0.928177  1.624060  0.099286    5.965809
147            0.571516  0.252230    0.926554  1.621220  0.096650    5.833968
21             0.571516  0.278683    0.924490  1.617608  0.106402    5.674512

     zhangs_metric
184       0.538875
160       0.545352
165       0.532492
147       0.526509
21        0.546562

c:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:109: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(